blog/urls.py
from django.urls import path
from .views import BlogHomeView, BlogPostView

app_name = 'blog'

urlpatterns = [
    path('', BlogHomeView, name='home'),
    path('<int:id>', BlogPostView, name='post'),
]

core/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views
app_name = 'core'

'''
router = DefaultRouter()
router.register('ammenities', views.AmmenitiesView,  basename='ammenities')
router.register('payment_methods', views.PaymentMethodsView,  basename='payment_methods')
router.register('library', views.LibraryView, basename='library')
'''
urlpatterns = [
    #path('api/', include(router.urls)),
    path('', views.HomeView, name='home'),
    path('terms-and-conditions', views.TandCView, name='tnc'),
    path('privacy-policy', views.PrivacyPolicyView, name='privacypolicy'),

    path('contact', views.ContactView, name='contact'),
    path('submit-testimonial', views.TestimonialsView, name='testimonial'),
    path('report-bug', views.BugReportView, name='reportbug'),
    path('faq', views.FAQView, name='faq'),
    path('faq/<int:id>', views.FAQDetailView , name='faqdetail'),

    path('libraries', views.LibrariesView, name='libraries'),
    path('library/<int:id>', views.LibraryView, name='library'),



    path('user-profile', views.UserProfileView, name='userprofile'),
    path('my-libraries', views.myLibraries, name='mylibraries'),
    path('hide-library/<int:id>', views.hideLibrary, name='hidelibrary'),
    path('show-library/<int:id>', views.showLibrary, name='showlibrary'),
    path('addlibrary/', views.addLibrary, name='addlibrary'),
    path('editlibrary/<int:id>', views.editLibrary, name='editlibrary'),
    path('deletelibrary/<int:id>', views.deleteLibrary, name='deletelibrary'),

    path('my-bookmarks', views.BookmarkView, name='bookmarks'),
    path('add-to-bookmarks/<int:id>', views.add_to_bookmark, name='addtobookmarks'),
    path('remove-from-bookmarks/<int:id>', views.remove_from_bookmark, name='removefrombookmarks'),

    path('compare-libraries', views.ComparisonView, name='compare'),
    path('add-to-compare/<int:id>', views.add_to_compare, name='addtocompare'),
    path('remove-from-compare/<int:id>', views.remove_from_compare, name='removefromcompare'),

]

exams/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

app_name = 'exams'

urlpatterns = [
    #path('api/', include(router.urls)),

    #path('previous-years', views.HomeView, name='previous_year'),
    path('test', views.testView, name='test'),
    path('current-affairs', views.CurrentAffairsView, name='currentaffairs'),
    path('previous-years', views.PreviousYearQAView, name='previousyear'),
    # path('download/<int:id>/<int:no>', views.download, name='download'),

]

liblocation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('exams/', include('exams.urls', namespace='exams')),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-166766626-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-166766626-1');
    </script>

	<title>Library Listing</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <meta content="" name="keywords">
    <meta content="" name="description">
    
    <!-- Favicon -->   
    <link href="{% static 'images/logo.png' %}" rel="shortcut icon"/>

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/color.css'%}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/icons.css'%}">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

	{% block extra_stylesheet %}
	{% endblock extra_stylesheet %}

</head>


<body>
    {% comment %}
    <div style="display:none">
        <img src="{% google_analytics %}" width="0" height="0" />
    </div>
    {% endcomment %}
    <div id="wrapper" class="mm-page mm-slideout">
	{% include "navbar.html" %}


    <!-- Messages -->   
	{% if messages %}
	<div class="">
        {% for message in messages %}

            <div class="notification {{ message.tags }} closeable">
				<p>{{ message }}</p>
				<a class="close"></a>
			</div>

        {% endfor %}
    </div>
	{% endif %}
    <!-- EndMessages -->


    <!-- Wrapper -->

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock extra_body %}
  
    {% include "footer.html" %}

    <!-- Back To Top Button -->
    <div id="backtotop"><a href="#"></a></div>

    </div>
    <!-- Wrapper -->
    {% include "scripts.html" %}
  
    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Container / Start -->
<div class="container" style="margin-top: 100px; margin-bottom: 100px">

	<div class="row">

		<!-- Contact Details -->
		<div class="col-md-6">

			<h4 class="headline margin-bottom-30">Contact Information</h4>

			<!-- Contact Details -->
			<div class="sidebar-textbox">
				<p>
                    Power2create Grievance Officer shall undertake all reasonable efforts to address your grievances at the earliest possible opportunity.

                    <br><br>You may contact us at:
                    <br>&emsp;Grievance Officer : Konark Kumar
                    <br>&emsp;Address : 12b 2nd Floor, Ram Durga Building, Jawahar Nagar,
                    <br>&emsp;Malka Ganj Chowk,
                    <br>&emsp;Delhi – 110007, India.

                    <br><br>Reach out to us in case of any queries.

</p>

				<ul class="contact-details">
					<li><i class="im im-icon-Phone-2"></i> <strong>Phone: </strong> <span>9818896523</span></li>
					<li><i class="im im-icon-Globe"></i> <strong>Web: power2create.in</strong> <span><a href="power2create.in"></a></span></li>
					<li><i class="im im-icon-Envelope"></i> <strong>E-Mail:</strong> <span><a href="#">Info@power2create.in</a></span></li>
				</ul>
			</div>

		</div>

		<!-- Contact Form -->
		<div class="col-md-6">

			<section id="contact">
				<h4 class="headline margin-bottom-35">Contact Form</h4>

				<div id="contact-message"></div>

					<form method="post" class="form-a contactForm" autocomplete="on">
                    {% csrf_token %}

					<div class="row">
						{% for field in contactform %}
                        <div>
                            {{ field.label }}
                            {{ field }}
                        </div>
                        {% endfor %}
					<button class="button margin-top-20 margin-bottom-20" type = "submit">Send</button>
                    </div>
					</form>
			</section>
		</div>
		<!-- Contact Form / End -->

	</div>

</div>
<!-- Container / End -->

{% endblock content %}

templates/faq.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


<!-- Titlebar
================================================== -->
<div id="titlebar">
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<h2>F.A.Q.</h2>


			</div>
		</div>
	</div>
</div>


<!-- Content
================================================== -->

<!-- Container -->
<div class="container">

	<div class="row">

		<div class="col-md-10">
{#			<h4 class="headline margin-top-0 margin-bottom-20">FAQs</h4>#}

			<!-- Toggles Container -->
			<div class="style-2">
                {% for faq in faqs %}
				<!-- Toggle 1 -->
				<div class="toggle-wrap">
					<span class="trigger "><a href="#">{{ forloop.counter }}. {{ faq.question }}<i class="sl sl-icon-plus"></i></a></span>
					<div class="toggle-container" style="display: none;">
						<p>
							{{ faq.get_short_content }}


							{% if faq.if_short_content == 'True' %}
                                <a href="{% url 'core:faqdetail' faq.id %}">
                                    &nbsp; Read More ...
                                </a>
                            {% endif %}
                        </p>

					</div>
				</div>
                {% endfor %}

			</div>
			<!-- Toggles Container / End -->
		</div>



</div>
</div>
<!-- Wrapper / End -->



<div id="mm-blocker" class="mm-slideout"></div>
{% endblock content %}

templates/faqdetail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="clearfix"></div>
<!-- Header Container / End -->

<div id="wrapper" class="mm-page mm-slideout">

<!-- Titlebar
================================================== -->
<div id="titlebar">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2>FAQ</h2>
			</div>
		</div>
	</div>
</div>

<!-- Content
================================================== -->
<div class="container" style="margin-bottom: 50px">
	<!-- Inline Elements
	================================================== -->
	<div class="row">
		<div class="col-md-12">
		<!-- Headline -->
		<h4 class="headline with-border margin-top-45 margin-bottom-25" style="text-align: center"> {{faq.question}} </h4>

            <p>
                {{faq.answer|escape|linebreaks }}
            </p>
		</div>
	</div>
</div>

</div>
<!-- Wrapper / End -->

<div id="mm-blocker" class="mm-slideout"></div>

{% endblock content %}

templates/footer.html
{% load static %}

<!-- Footer
================================================== -->
<div id="footer" class="dark">
	<!-- Main -->
	<div class="container">
		<div class="row">
			<div class="col-md-5 col-sm-6">
				<img class="footer-logo" src="{%  static 'images/logo2.png' %}" alt="">
				<br><br>
				<p>Compare the best chosen Libraries around you and select the ideal one for yourself. <br><br> Happy Learning !!</p>
			</div>

			<div class="col-md-4 col-sm-6 ">
				<h4>Helpful Links</h4>
				<ul class="footer-links">
					<li><a href="{% url 'account_login' %}">Login</a></li>
					<li><a href="{% url 'account_signup' %}">Sign Up</a></li>
					<li><a href="{% url 'core:userprofile' %}">My Account</a></li>
					<li><a href="{% url 'core:addlibrary' %}">Add Library</a></li>
					<li><a href="{% url 'core:bookmarks' %}">Bookmarks</a></li>
                </ul>
                <ul class="footer-links">
                    <li><a href="{% url 'core:privacypolicy' %}">Privacy Policy</a></li>
					<li><a href="{% url 'core:faq' %}">FAQ</a></li>
                    <li><a href="{% url 'core:tnc' %}">Terms and Conditions</a></li>
					<li><a href="{% url 'core:reportbug' %}">Report a Bug</a></li>
                    <li><a href="{% url 'core:contact' %}">Contact</a></li>
				</ul>

				<div class="clearfix"></div>
			</div>

			<div class="col-md-3  col-sm-12">
				<h4>Contact Us</h4>
				<div class="text-widget">
					<span>12b 2nd Floor, Ram Durga Building, Jawahar Nagar, Malka Ganj</span> <br>
					Phone: <span> +91-9818896523 </span><br>
					E-Mail:<span> <a href="#">Info@power2create.in</a> </span><br>
				</div>

				<ul class="social-icons margin-top-20">
					<li><a class="facebook" href="#"><i class="icon-facebook"></i></a></li>
					<li><a class="twitter" href="#"><i class="icon-twitter"></i></a></li>
                </ul>

			</div>

		</div>

		<!-- Copyright -->
		<div class="row">
			<div class="col-md-12">
				<div class="copyrights">© 2020 Library Nearby. All Rights Reserved.</div>
			</div>
		</div>

	</div>

</div>
<!-- Footer / End -->

templates/navbar.html
{% load static %}

<!-- Wrapper -->
<div id="wrapper" class="mm-page mm-slideout">

<!-- Header Container
================================================== -->
<header id="header-container" class="header-style-2">

	<!-- Header -->
	<div id="header" class="">
		<div class="container">

			<!-- Left Side Content -->
			<div class="left-side">

				<!-- Logo -->
				<div id="logo" class="margin-top-10">
					<a href="index.html"><img src="{% static 'images/logo.png' %}" alt=""></a>
                </div>

				<!-- Mobile Navigation -->
				<div class="mmenu-trigger">
					<button class="hamburger hamburger--collapse" type="button">
						<span class="hamburger-box">
							<span class="hamburger-inner"></span>
						</span>
					</button>
				</div>

			</div>
			<!-- Left Side Content / End -->

            <!-- Right Side Content / End -->
			<div class="right-side">
				<ul class="header-widget">
                    <!--
					<li>
						<i class="sl sl-icon-call-in"></i>
						<div class="widget-content">
							<span class="title">Questions?</span>
							<span class="data">(123) 123-456 </span>
						</div>
					</li>

					<li>
						<i class="sl sl-icon-location"></i>
						<div class="widget-content">
							<span class="title">Our Office</span>
							<span class="data">45 Park Avenue, NY</span>
						</div>
					</li>
                    -->
					<li class="with-btn"><a href="{% url 'core:addlibrary' %}" class="button border">Add Library</a></li>
                </ul>

            </div>
			<!-- Right Side Content / End -->

		</div>

		<!-- Main Navigation -->
		<nav id="navigation" class="style-2">
			<div class="container">
					<ul id="responsive">

						<li><a href="{% url 'core:home' %}" {% if request.resolver_match.view_name == 'core:home' %}class="current"{% endif %}>Home</a>
						<!--	<ul>
								<li><a href="index.html">About</a></li>
								<li><a href="index-2.html">Services</a></li>
								<li><a href="index-3.html">Search</a></li>
							</ul>
							-->
						</li>

						<li><a href="{% url 'core:libraries' %}" {% if request.resolver_match.view_name == 'core:libraries' %}class="current"{% endif %}>Libraries</a>
							<!--
                            <ul>
								<li><a href="#">For Rent</a>

									<ul>
										<li><a href="listings-list-with-sidebar.html">With Sidebar</a></li>
										<li><a href="listings-list-with-map.html">With Map</a></li>
										<li><a href="listings-list-full-width.html">Full Width</a></li>
									</ul>
								</li>
								<li><a href="#">For Sale</a>
								</li>
							</ul> -->
						</li>
                                            <li>
                            <a href="{% url 'blog:home' %}" {% if request.resolver_match.view_name == 'blog:home' %}class="current"{% endif %}>Blog</a>
						</li>
                        <li>
                            <a href="{% url 'exams:previousyear' %}" {% if request.resolver_match.view_name == 'exams:previousyear' %}class="current"{% endif %}>Previous Year Q/A</a>
						</li>
                        <li>
                            <a href="{% url 'exams:currentaffairs' %}" {% if request.resolver_match.view_name == 'exams:currentaffairs' %}class="current"{% endif %}>Current Affairs</a>
						</li>
                        <li>
                            <a href="{% url 'core:compare' %}" {% if request.resolver_match.view_name == 'core:compare' %}class="current"{% endif %}>Compare</a>
						</li>
						<li>
                            <a href="{% url 'core:contact' %}" {% if request.resolver_match.view_name == 'core:contact' %}class="current"{% endif %}>Contact Us</a>
						</li>
<!-- 						<li class="right-side-menu-item"><a href="login-register.html" class="sign-in"><i class="fa fa-user"></i> Log In / Register</a></li> -->
					</ul>
			</div>
		</nav>

        <nav id="navigation" class="style-2 cloned unsticky">
			<div class="container">
					<ul id="responsive"><a href="{% url 'core:home' %}" class="sticky-logo"><img src="{% static 'images/logo2.png' %}" alt=""></a>

						<li><a href="{% url 'core:home' %}" {% if request.resolver_match.view_name == 'core:home' %}class="current"{% endif %}>Home</a>
							<ul>
								<li><a href="#about">About</a></li>
								<li><a href="#services">Services</a></li>
								<li><a href="#search">Search</a></li>
							</ul>
						</li>

						<li><a href="{% url 'core:libraries' %}" {% if request.resolver_match.view_name == 'core:libraries' %}class="current"{% endif %}>Libraries</a>
							<!--<ul>
								<li><a href="#">For Rent</a>

									<ul>
										<li><a href="listings-list-with-sidebar.html">With Sidebar</a></li>
										<li><a href="listings-list-with-map.html">With Map</a></li>
										<li><a href="listings-list-full-width.html">Full Width</a></li>
									</ul>
								</li>
								<li><a href="#">For Sale</a>
								</li>
							</ul>-->
						</li>
                        <li>
                            <a href="{% url 'blog:home' %}" {% if request.resolver_match.view_name == 'blog:home' %}class="current"{% endif %}>Blog</a>
						</li>
                        <li>
                            <a href="{% url 'exams:previousyear' %}" {% if request.resolver_match.view_name == 'exams:previousyear' %}class="current"{% endif %}>Previous Year Q/A</a>
						</li>
                        <li>
                            <a href="{% url 'exams:currentaffairs' %}" {% if request.resolver_match.view_name == 'exams:currentaffairs' %}class="current"{% endif %}>Current Affairs</a>
						</li>
                        <li>
                            <a href="{% url 'core:compare' %}" {% if request.resolver_match.view_name == 'core:compare' %}class="current"{% endif %}>Compare</a>
						</li>
						<li>
                            <a href="{% url 'core:contact' %}" {% if request.resolver_match.view_name == 'core:contact' %}class="current"{% endif %}>Contact Us</a>
						</li>
<!-- 						<li class="right-side-menu-item"><a href="login-register.html" class="sign-in"><i class="fa fa-user"></i> Log In / Register</a></li> -->
					</ul>
			</div>
		</nav>

		<!-- User Menu -->
		<div class="container">
			<div class="row">
				<div class="user-menu-container">
					<div class="user-menu">
                        {% if request.user.is_authenticated %}
                            <div class="user-name">Hi {{ request.user.username }},</div>
                            <ul>
                                <li><a href="{% url 'core:userprofile' %}"><i class="sl sl-icon-user"></i> My Profile</a></li>
                                <li><a href="{% url 'core:bookmarks' %}"><i class="sl sl-icon-star"></i> Bookmarks</a></li>
                                <li><a href="{% url 'core:mylibraries' %}"><i class="sl sl-icon-docs"></i> My Libraries</a></li>
                                <li><a href="{% url 'account_logout' %}"><i class="sl sl-icon-power"></i> Log Out</a></li>
                            </ul>
                        {% else %}
                            <a href="{% url 'account_login' %}"><div class="user-name">
                            Sign-in</div></a>
                        {% endif %}
					</div>
				</div>
			</div>
		</div>
		<!-- User Menu / End -->

		<div class="clearfix"></div>
		<!-- Main Navigation / End -->
	</div>
	<!-- Header / End -->

</header>
<div class="clearfix"></div>
<!-- Header Container / End -->

</div>
<!-- Wrapper / End -->




<!-- Scripts
================================================== -->
<script type="text/javascript" src="{%  static 'scripts/chosen.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/custom.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/daterangepicker.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/dropzone.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/gmaps_api_v3.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/hoverIntent.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/infobox.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/jquery.counterup.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/jquery.jpanelmenu.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/jquery-2.2.0.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/jquery-3.4.1.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/jquery-migrate-3.1.0.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/magnific-popup.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/maps.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/markerclusterer.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/masonry.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/mmenu.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/moment.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/quantityButtons.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/rangeSlider.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/slick.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/sticky-kit.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/switcher.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/tooltips.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/waypoints.min.js' %}"></script>


<div id="mm-blocker" class="mm-slideout"></div>

<div id="tiptip_holder" style="max-width:200px;">
    <div id="tiptip_arrow">
        <div id="tiptip_arrow_inner">
        </div>
    </div>
    <div id="tiptip_content"></div></div>

templates/reportbug.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Container / Start -->
<div class="container" style="margin-top: 100px; margin-bottom: 100px">

	<div class="row">

		<!-- Contact Details -->
		<div class="col-md-4">

			<h4 class="headline margin-bottom-30">Find Us There</h4>

			<!-- Contact Details -->
			<div class="sidebar-textbox">
				<p>Power2create Grievance Officer shall undertake all reasonable efforts to address your grievances at the earliest possible opportunity. You may contact it at:

<br>Grievance Officer: Konark Kumar
<br>Address: 12b 2nd Floor, Ram Durga building, Jawahar nagar, Malka Ganj Chowk, Delhi – 110007, Delhi, India.



<br>Reach out to us on Info@power2create.in, in case of any queries.</p>

				<ul class="contact-details">
					<li><i class="im im-icon-Phone-2"></i> <strong>Phone:</strong> <span>8178340031 </span></li>
					<li><i class="im im-icon-Globe"></i> <strong>Web:</strong> <span><a href="#">www.powe2create.com</a></span></li>
					<li><i class="im im-icon-Envelope"></i> <strong>E-Mail:</strong> <span><a href="#">Info@power2create.in</a></span></li>
				</ul>
			</div>

		</div>

		<!-- Contact Form -->
		<div class="col-md-8">

			<section id="contact">
				<h4 class="headline margin-bottom-35"> Report a Bug </h4>

				<div id="contact-message"></div>

					<form method="post" name="contactform" enctype="multipart/form-data">

                    {% csrf_token %}
                        {% for field in bugreportform %}
                            <label>{{ field.label }}</label>
                            <div>
                                {{ field }}
                                {{ field.errors }}
                            </div>
                        {% endfor %}


					<button class="button margin-top-20 margin-bottom-20" type = "submit">Report Bug</button>

					</form>
			</section>
		</div>
		<!-- Contact Form / End -->

	</div>

</div>
<!-- Container / End -->

{% endblock content %}

templates/scripts.html
{% load static %}

<!-- Scripts
================================================== -->
<script type="text/javascript" src="{%  static 'scripts/chosen.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/custom.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/daterangepicker.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/dropzone.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/gmaps_api_v3.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/hoverIntent.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/infobox.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/jquery.counterup.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/jquery.jpanelmenu.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/jquery-2.2.0.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/jquery-3.4.1.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/jquery-migrate-3.1.0.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/magnific-popup.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/maps.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/markerclusterer.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/masonry.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/mmenu.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/moment.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/quantityButtons.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/rangeSlider.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/slick.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/sticky-kit.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/switcher.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/tooltips.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'scripts/waypoints.min.js' %}"></script>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&amp;language=en"></script>


<!-- Bootstrap-->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>