blog/urls.py
from django.urls import path
from .views import BlogHomeView, BlogPostView

app_name = 'blog'

urlpatterns = [
    path('', BlogHomeView, name='home'),
    path('<int:id>', BlogPostView, name='post'),
]

core/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views
app_name = 'core'

'''
router = DefaultRouter()
router.register('ammenities', views.AmmenitiesView,  basename='ammenities')
router.register('payment_methods', views.PaymentMethodsView,  basename='payment_methods')
router.register('library', views.LibraryView, basename='library')
'''
urlpatterns = [
    #path('api/', include(router.urls)),
    path('', views.HomeView, name='home'),
    path('terms-and-conditions', views.TandCView, name='tnc'),
    path('privacy-policy', views.PrivacyPolicyView, name='privacypolicy'),

    path('contact', views.ContactView, name='contact'),
    path('submit-testimonial', views.TestimonialsView, name='testimonial'),
    path('report-bug', views.BugReportView, name='reportbug'),
    path('faq', views.FAQView, name='faq'),
    path('faq/<int:id>', views.FAQDetailView , name='faqdetail'),

    path('libraries', views.LibrariesView, name='libraries'),
    path('library/<int:id>', views.LibraryView, name='library'),



    path('user-profile', views.UserProfileView, name='userprofile'),
    path('my-libraries', views.myLibraries, name='mylibraries'),
    path('hide-library/<int:id>', views.hideLibrary, name='hidelibrary'),
    path('show-library/<int:id>', views.showLibrary, name='showlibrary'),
    path('addlibrary/', views.addLibrary, name='addlibrary'),
    path('editlibrary/<int:id>', views.editLibrary, name='editlibrary'),
    path('deletelibrary/<int:id>', views.deleteLibrary, name='deletelibrary'),

    path('my-bookmarks', views.BookmarkView, name='bookmarks'),
    path('add-to-bookmarks/<int:id>', views.add_to_bookmark, name='addtobookmarks'),
    path('remove-from-bookmarks/<int:id>', views.remove_from_bookmark, name='removefrombookmarks'),

    path('compare-libraries', views.ComparisonView, name='compare'),
    path('add-to-compare/<int:id>', views.add_to_compare, name='addtocompare'),
    path('remove-from-compare/<int:id>', views.remove_from_compare, name='removefromcompare'),

]

liblocation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('exams/', include('exams.urls', namespace='exams')),
]

templates/dashboard/addlibrary.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
    <style>
.tip {
  position: relative;
  display: inline-block;
  border-bottom: 5px dotted black;
}

.tip .data-tip-content {
  visibility: hidden;
  width: 300px;
  background-color: black;
  color: #fff;
  text-align: center;
  border-radius: 15px;
  padding: 5px 0;
    line-height: 20px;

  /* Position the tooltip */
  position: absolute;
  z-index: 1;
}

.tip:hover .data-tip-content {
  visibility: visible;
}
</style>


<style>

#map {
    height: 300px;
    position: relative;
    padding-top: 20px;
}
</style>
   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.3/jquery.timepicker.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.3/jquery.timepicker.min.js"></script>


<!-- Titlebar
================================================== -->
<div id="titlebar" class="submit-page">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2><i class="fa fa-plus-circle"></i> Publish Library</h2>
			</div>
		</div>
	</div>
</div>


<!-- Content
================================================== -->
<div class="container">
<form method="post" enctype="multipart/form-data">
{% csrf_token %}
<div class="row">

	<!-- Submit Page -->
	<div class="col-md-12">
		<div class="submit-page">
           <h3> Basic Information </h3>

		<!-- Section -->
          <div class="submit-section">
              <!-- Title -->
			<div class="form">
				<h5>Library Name</h5>
                {% render_field form.name class="search-field" placeholder="Library Name" type="text" %}
                {{ form.name.errors }}
			</div>

			<!-- Row -->
			<div class="row with-forms">

				<!-- Status -->
				<div class="col-md-3">
					<h5>First Name</h5>
                    {% render_field form.owner_fname class="search-field" placeholder="First Name" type="text" %}
                    {{ form.owner_fname.errors }}
				</div>

                <div class="col-md-3">
					<h5>Last Name</h5>
                    {% render_field form.owner_lname class="search-field" placeholder="Last Name" type="text" %}
                    {{ form.owner_lname.errors }}
				</div>

                <div class="col-md-6">
					<h5>Email ID</h5>
                    {% render_field form.email class="search-field" type="email" placeholder="Email" %}
                    {{ form.email.errors }}
				</div>

                <div class="col-md-4">
					<h5>Phone</h5>
                    {% render_field form.mobile_no class="search-field" type="tel" placeholder="Mobile Number" %}
                    {{ form.mobile_no.errors }}
				</div>

				<div class="col-md-4">
					<h5>Landline</h5>
                    {% render_field form.landline class="search-field" type="tel" placeholder="Landline" %}
                    {{ form.landline.errors }}
				</div>

                <div class="col-md-4">
					<h5>Main Image <span>(Of Library)</span></h5>
                    {% render_field form.main_image id="main-image" type="file" accept="image/gif, image/jpeg, image/png" %}
                    {{ form.main_image.errors }}
                </div>

                <div class="col-md-12">
                    <h5>Website   <span>(optional)</span></h5>
                    {% render_field form.website class="search-field" id="website" type="url" placeholder="Website URL" %}
                    {{ form.website.errors }}
                </div>

                <div class="col-md-12">
                    <h5>Library Images</h5>
                    {% render_field imagesform.image class="dropzone" id="website" %}
                    {{ imagesform.image.errors }}
                </div>



			</div>
			<!-- Row / End -->

		</div>
		<!-- Section / End -->


		<!-- Section -->
            <h3>Location<i class="tip"> <span class="data-tip-content"> Add the location of your library</span></i></h3>
		<div class="submit-section">

			<!-- Row -->
			<div class="row with-forms">

				<!-- Address -->
				<div class="col-md-12">
					<h5> Address 1</h5>
                    {% render_field form.addr1 type="text" %}
                    {{ form.addr1.errors }}
                    <h5> Address 2</h5>
                    {% render_field form.addr2 type="text" %}
                    {{ form.addr2.errors }}
				</div>

				<!-- City -->
				<div class="col-md-4">
					<h5>City</h5>
                    {% render_field form.city type="text" placeholder="City" %}
                    {{ form.city.errors }}
				</div>

				<!-- City -->
				<div class="col-md-4">
					<h5>State</h5>
                    {% render_field form.state type="text" placeholder="State" %}
                    {{ form.state.errors }}
				</div>

				<!-- Zip-Code -->
				<div class="col-md-4">
					<h5>PIN Code</h5>
                    {% render_field form.pincode id="zip" name="zip" type="text" pattern="[0-9]*" placeholder="PIN" %}
                    {{ form.pincode.errors }}
				</div>

                <div class="col-md-5">
                    <h5>Latitude</h5>
                    <input type="number" step="any" id="latitude" placeholder="Latitude" name="latitude" required/>
                </div>

                <div class="col-md-5">
                    <h5>Longitude</h5>
                    <input type="number" step="any" id="longitude" placeholder="Longitude" name="longitude" required/>
                </div>

                <div class="col-md-2" style="padding-top: 40px">
                    <input style="line-height: 20px" type="button" value="Jump" onClick="updateLatLng(document.getElementById('latitude').value,document.getElementById('longitude').value,1)">
                </div>

                <div class="divider" style="padding-top: 20px;">
                <div id="map"></div>
                    <h5>Or, click on your location in the map</h5>
                </div>


			</div>
			<!-- Row / End -->

		</div>
		<!-- Section / End -->


		<!-- Section -->
		<h3>Detailed Information</h3>
		<div class="submit-section">

			<!-- Description -->
			<div class="form">
				<h5>Description</h5>
                {% render_field form.library_description class="WYSIWYG" name="summary" cols="40" rows="3" id="summary" spellcheck="true" required='' %}
                {{ form.library_description.errors }}
			</div>


            <div class="row with-forms">
               <div class="col-md-4">
                   <h5>Number Of Seats<i class="tip"><span class="data-tip-content">Add the number of seats in your library</span></i></h5>
                   {% render_field form.no_of_seats id="seats" placeholder="Seats" %}
                   {{ form.no_of_seats.errors }}
                </div>
                <div class="col-md-4">
                    <h5>Opening Time<i class="tip"><span class="data-tip-content">Opening time of your library</span></i></h5>
                    {% render_field form.opening_time type="text" id="openingtime" class="from-control" placeholder="Hr:Min" %}
                    {{ form.opening_time.errors }}
                </div>
               <div class="col-md-4">
                   <h5>Closing Time<i class="tip"><span class="data-tip-content">Closing time of your library</span></i></h5>
                   {% render_field form.closing_time type="text" id="closingtime" class="from-control" placeholder="Hr:Min" %}
                   {{ form.closing_time.errors }}
                </div>

               <div class="col-md-3">
                   <h5>One Time Charges</h5>
                  {% render_field form.non_refundable_charges id="non-ref-charges" type="number" placeholder="Rs. " %}
                   {{ form.non_refundable_charges.errors }}
               </div>
		       <div class="col-md-3">
                   <h5>Refund Policy</h5>
                   {% render_field form.refund_policy  %}
                   {{ form.refund_policy.errors }}
               </div>
               <div class="col-md-3">
                   <h5>Min Price Range</h5>
                   {% render_field form.min_price_range id="min-range" type="number" placeholder="Rs. " %}
                   {{ form.min_price_range.errors }}
               </div>
               <div class="col-md-3">
                   <h5>Max Price Range</h5>
                   {% render_field form.max_price_range id="max-range" type="number" placeholder="Rs. " %}
                   {{ form.max_price_range.errors }}
               </div>
        </div>
            {% comment %}
            {% render_field form.ammenities %}
            {% render_field form.payment_methods %}
            {% render_field form.opening_days %}
            {% endcomment %}
			<!-- Checkboxes -->
			<h5 class="margin-top-30">Amenities</h5>
			<div class="checkboxes in-row margin-bottom-20">

                {% for amenity in amenities %}
				<input id="amenities-{{ forloop.counter }}" type="checkbox" name="amenities" value={{ amenity.id }}>
				<label for="amenities-{{ forloop.counter }}">{{ amenity.title }}</label>
                {% endfor %}

			</div>

            <h5 class="margin-top-30">Payment Methods</h5>
			<div class="checkboxes in-row margin-bottom-20">


                {% for payment_method in payment_methods %}
				<input id="payment_methods-{{ forloop.counter }}" type="checkbox" name="payment_methods" value={{ payment_method.id }}>
				<label for="payment_methods-{{ forloop.counter }}">{{ payment_method.title }}</label>
                {% endfor %}
                {{ form.payment_methods.erros }}
			</div>
			<!-- Checkboxes / End -->


            <h5 class="margin-top-30">Opening Days</h5>
            <div class="checkboxes in-row margin-bottom-20">

            {% for day in opening_days %}
               <input  type="checkbox" name="opening_days" id="openings_days-{{day.id}} openings_days" value={{ day.id }} />
               <label for="openings_days-{{day.id}}">{{day.day}}</label><br />
            {% endfor %}
            {{ form.opening_days.erros }}
            </div>


        </div>
        <h3>Social Media</h3>
            <div class="submit-section">
                <div class="col-md-4">
                    <h5>Facebook</h5>
                    {% render_field form.fb_url id="fb" type="url" placeholder="Facebook URL" %}
                    {{ form.fb_url.errors }}
                </div>

                <div class="col-md-4">
                    <h5>Instagram</h5>
                    {% render_field form.insta id="fb" type="url" placeholder="Instagram URL" %}
                    {{ form.insta.errors }}
                </div>

                <div class="col-md-4">
                    <h5>Google Map<i class="tip"><span class="data-tip-content"> Google Maps link of your library"</span></i></h5>
                    {% render_field form.google_map id="fb" type="url" placeholder="Google Maps URL" %}
                    {{ form.google_map.errors }}
                </div>

            </div>
            <button class="button fullwidth margin-top-5" type="submit">Publish Library</button>
        <br><br><br>


</div>



  </div>
</div>
</form>
</div>

		<!-- Section / End -->

        {% comment %}
		<!-- Section -->
		<h3>Contact Details</h3>
		<div class="submit-section">

			<!-- Row -->
			<div class="row with-forms">

				<!-- Name -->
				<div class="col-md-4">
					<h5>Name</h5>
					<input type="text">
				</div>

				<!-- Email -->
				<div class="col-md-4">
					<h5>E-Mail</h5>
					<input type="text">
				</div>

				<!-- Name -->
				<div class="col-md-4">
					<h5>Phone <span>(optional)</span></h5>
					<input type="text">
				</div>

			</div>
			<!-- Row / End -->

		</div>
		<!-- Section / End -->
		 {% endcomment %}


            <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
   integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
   crossorigin=""/>
            <script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script> <!-- Orginal: http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js -->
<script>
var tileLayer = new L.TileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> Contributors'
});
//remember last position
var rememberLat = document.getElementById('latitude').value;
var rememberLong = document.getElementById('longitude').value;
if( !rememberLat || !rememberLong ) { rememberLat = 28.6; rememberLong = 77.25;}
var map = new L.Map('map', {
'center': [rememberLat, rememberLong],
'zoom': 11,
'layers': [tileLayer]
});
var marker = L.marker([rememberLat, rememberLong],{
draggable: true
}).addTo(map);
marker.on('dragend', function (e) {
updateLatLng(marker.getLatLng().lat, marker.getLatLng().lng);
});
map.on('click', function (e) {
marker.setLatLng(e.latlng);
updateLatLng(marker.getLatLng().lat, marker.getLatLng().lng);
});
function updateLatLng(lat,lng,reverse) {
if(reverse) {
marker.setLatLng([lat,lng]);
map.panTo([lat,lng]);
} else {
document.getElementById('latitude').value = marker.getLatLng().lat;
document.getElementById('longitude').value = marker.getLatLng().lng;
map.panTo([lat,lng]);
}
}
</script>


<script type="text/javascript">
    $( "#openingtime" ).timepicker({ timeFormat: 'H:mm:ss' });
    $("#closingtime").timepicker({ timeFormat: 'H:mm:ss' });
</script>

<script type="text/javascript">
$(document).ready(function () {
    $('#openings_days').click(function() {
      checked = $("input[type=checkbox]:checked").length;

      if(!checked) {
        alert("You must check at least one checkbox.");
        return false;
      }

    });
});

</script>
{% endblock content %}

templates/dashboard/bookmarks.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- Titlebar
================================================== -->
<div id="titlebar">
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<h2>Bookmarked Listings</h2>


			</div>
		</div>
	</div>
</div>


<!-- Content
================================================== -->
<div class="container">
	<div class="row">


		{% include 'dashboard/dashboardsidenav.html' %}
		<div class="col-md-8">
			<table class="manage-table bookmarks-table responsive-table">

				<tr>
					<th><i class="fa fa-file-text"></i> Library</th>
					<th></th>
				</tr>

            {% if bookmark %}
                {% for library in bookmark.libraries.all %}
				<!-- Item #1 -->
				<tr>
					<td class="title-container">
						<img src="{{ library.main_image.url }}" alt="">
						<div class="title">
							<h4><a href="{% url 'core:library' library.id %}">{{ library.name }}</a></h4>
							<span>{{ library.city }}</span>
							<span class="table-property-price">Rs {{ library.min_monthly_charges }}</span>
						</div>
					</td>
					<td class="action">
						<a href="{% url 'core:removefrombookmarks' library.id %}" class="delete"><i class="fa fa-remove"></i> Remove</a>
					</td>
				</tr>
                {% endfor %}
            {% else %}
                <tr>
					<td>
							<h4><a href="#">You Haven't Bookmarked any Property !</a></h4>

					</td>
				</tr>
            {% endif %}

			</table>
		</div>

	</div>
</div>

{% endblock content %}

templates/dashboard/comparelibraries.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


    <!-- Wrapper -->
    <div id="wrapper" class="mm-page mm-slideout">


    <!-- Titlebar
    ================================================== -->
    <div class="parallax titlebar"
	data-background="{% static 'images/comp.jpg' %}"
	data-color="#333333"
	data-color-opacity="0.7"
	data-img-width="800"
	data-img-height="505">
    <div id="titlebar">
        <div class="container">
            <div class="row">
                <div class="col-md-12">

                    <h2>Comparing Libraries</h2>

                </div>
            </div>
        </div>
    </div>
    </div>


    <!-- Content
    ================================================== -->
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <!-- Compare List -->
                <div class="compare-list-container">
                    <ul id="compare-list">

                        <li class="compare-list-libraries">
                            <div class="blank-div"></div>

                            {% if library1 %}
                            <div>

                                    <div class="clp-img">
                                        <a href="{% url 'core:library' library1.id %}"><img src="{{ library1.main_image.url }}" alt=""></a>
                                        <a href="{% url 'core:removefromcompare' library1.id %}"><span class="remove-from-compare"><i class="fa fa-close"></i></span></a>
                                    </div>

                                    <div class="clp-title">
                                        <h4>{{ library1.name }}</h4>
                                        <span>{{ library1.min_monthly_charges }}</span>
                                    </div>

                            </div>
                            {% endif %}

                            {% if library2 %}
                            <div>
                                <a href="#">
                                    <div class="clp-img">
                                        <a href="{% url 'core:library' library2.id %}"><img src="{{ library2.main_image.url }}" alt=""></a>
                                        <a href="{% url 'core:removefromcompare' library2.id %}"><span class="remove-from-compare"><i class="fa fa-close"></i></span></a>
                                    </div>
                                    <div class="clp-title">
                                        <h4>{{ library2.name }}</h4>
                                        <span>{{ library2.min_monthly_charges }}</span>
                                    </div>
                                </a>
                            </div>
                            {% endif %}

                            {% if library3 %}
                            <div>
                                <a href="#">
                                    <div class="clp-img">
                                        <a href="{% url 'core:library' library3.id %}"><img src="{{ library3.main_image.url }}" alt=""></a>
                                        <a href="{% url 'core:removefromcompare' library3.id %}"><span class="remove-from-compare"><i class="fa fa-close"></i></span></a>
                                    </div>
                                    <div class="clp-title">
                                        <h4>{{ library3.name }}</h4>
                                        <span>{{ library3.min_monthly_charges }}</span>
                                    </div>
                                </a>
                            </div>
                            {% endif %}
                        </li>

                        <li>
                            <div>No of Seats</div>
                            {% if library1 %}<div>{{ library1.no_of_seats }}</div>{% endif %}
                            {% if library2 %}<div>{{ library2.no_of_seats }}</div>{% endif %}
                            {% if library3 %}<div>{{ library3.no_of_seats }}</div>{% endif %}

                        </li>

                        <li>
                            <div>Opening Time</div>
                            {% if library1 %}<div>{{ library1.opening_time }}</div>{% endif %}
                            {% if library2 %}<div>{{ library2.opening_time }}</div>{% endif %}
                            {% if library3 %}<div>{{ library3.opening_time }}</div>{% endif %}
                        </li>

                        <li>
                            <div>Closing Time</div>
                            {% if library1 %}<div>{{ library1.closing_time }}</div>{% endif %}
                            {% if library2 %}<div>{{ library2.closing_time }}</div>{% endif %}
                            {% if library3 %}<div>{{ library3.closing_time }}</div>{% endif %}
                        </li>

                        <li>
                            <div>Non Refundable Charges</div>
                            {% if library1 %}<div>{{ library1.non_refundable_charges }}</div>{% endif %}
                            {% if library2 %}<div>{{ library2.non_refundable_charges }}</div>{% endif %}
                            {% if library3 %}<div>{{ library3.non_refundable_charges }}</div>{% endif %}
                        </li>

                        {% for ammenity in ammenities %}
                        <li>
                            <div>{{ ammenity.title }}</div>
                            {% if library1 %}<div>{% if ammenity in library1.ammenities.all %}<span class="available"></span>{% else %}<span class="not-available"></span>{% endif %}</div>{% endif %}
                            {% if library2 %}<div>{% if ammenity in library2.ammenities.all %}<span class="available"></span>{% else %}<span class="not-available"></span>{% endif %}</div>{% endif %}
                            {% if library3 %}<div>{% if ammenity in library3.ammenities.all %}<span class="available"></span>{% else %}<span class="not-available"></span>{% endif %}</div>{% endif %}

                        </li>
                        {% endfor %}

                    </ul>
                </div>
                <!-- Compare List / End -->

            </div>
        </div>
    </div>



    </div>
    <!-- Wrapper / End -->



    <div id="mm-blocker" class="mm-slideout"></div>








{% endblock content %}

templates/dashboard/dashboardsidenav.html
<!-- Widget -->
    <div class="col-md-4">
        <div class="sidebar left">

            <div class="my-account-nav-container">

                <ul class="my-account-nav">
                    <li class="sub-nav-title">Manage Account</li>
                    <li><a href="{% url 'core:userprofile' %}" {% if request.resolver_match.view_name == 'core:userprofile' %}class="current"{% endif %}><i class="sl sl-icon-user"></i> My Profile</a></li>
{#                    <li><a href="{% url 'core:bookmarks' %}" {% if request.resolver_match.view_name == 'core:bookmarks' %}class="current"{% endif %}><i class="sl sl-icon-star"></i> Bookmarked Listings</a></li>#}
                </ul>


                <ul class="my-account-nav">
                    <li class="sub-nav-title">Manage Listings</li>
                    <li><a href="{% url 'core:mylibraries' %}" {% if request.resolver_match.view_name == 'core:myproperties' %}class="current"{% endif %}><i class="sl sl-icon-docs"></i> My Libraries</a></li>
                    <li><a href="{% url 'core:addlibrary' %}" {% if request.resolver_match.view_name == 'core:addproperty' %}class="current"{% endif %}><i class="sl sl-icon-action-redo"></i> Submit New Library</a></li>
                </ul>


                <ul class="my-account-nav">
                    <li><a href="{% url 'account_change_password' %}"><i class="sl sl-icon-lock"></i> Change Password</a></li>
                    <li><a href="{% url 'account_logout' %}"><i class="sl sl-icon-power"></i> Log Out</a></li>
                </ul>

            </div>

        </div>
    </div>

templates/dashboard/mylibraries.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


    <!-- Titlebar================================================== -->
    <div id="titlebar">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2>My Libraries</h2>
                </div>
            </div>
        </div>
    </div>


    <!-- Content
    ================================================== -->
    <div class="container">
        <div class="row">


            {% include 'dashboard/dashboardsidenav.html' %}

            <div class="col-md-8">
                <table class="manage-table responsive-table">

                    <tr>
                        <th><i class="fa fa-file-text"></i> Library</th>
                        <th class="expire-date"><i class="fa fa-calendar"></i> Views</th>
                        <th></th>
                    </tr>

                    {% for library in libraries %}
                    <!-- Item #1 -->
                    <tr>
                        <td class="title-container">
                            <img src="{{ library.main_image.url }}" alt="">
                            <div class="title">
                                <h4><a href="{% url 'core:library' library.id %}">{{ library.name }}</a></h4>
                                <span>{{ library.city }} </span>

                                {% if library.rejected %}
                                    <span class="table-property-price">Rejected : {{ library.rejection_reason }}</span>
                                {% else %}
                                    {% if library.verified %}
                                    <span class="table-property-price">Approved</span>
                                    {% else %}
                                        <span class="table-property-price">Waiting Approval</span>
                                    {% endif %}
                                {% endif %}
                            </div>
                        </td>
                        <td class="expire-date">{{ library.views }}</td>
                        <td class="action">
                            <a href="{% url 'core:editlibrary' library.id %}"><i class="far fa-edit"></i> Edit</a>
                            {% if library.visible %}
                            <a href="{% url 'core:hidelibrary' library.id %}"><i class="fa  fa-eye-slash"></i> Hide</a>
                            {% else %}
                            <a href="{% url 'core:showlibrary' library.id %}"><i class="fa  fa-eye-slash"></i> Show</a>
                            {% endif %}
                            <a href="{% url 'core:deletelibrary' library.id %}" class="delete"><i class="fa fa-remove"></i> Delete</a>
                        </td>
                    </tr>
                    {% endfor %}

                </table>
                <a href="{% url 'core:addlibrary' %}" class="margin-top-40 button">Submit New Library</a>
            </div>

        </div>
    </div>



{% endblock content %}

templates/dashboard/userprofile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Titlebar
================================================== -->
<div id="titlebar">
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<h2>My Profile</h2>


			</div>
		</div>
	</div>
</div>


<!-- Content
================================================== -->
<div class="container">
	<div class="row">


		{% include 'dashboard/dashboardsidenav.html' %}
		<div class="col-md-8">
			<div class="row">


            <div class="col-md-8 my-profile">
                <h4 class="margin-top-0 margin-bottom-30">My Account</h4>
                <form class="form-a contactForm" action="" method="post" role="form">
                    {% csrf_token %}

                    {% for field in form %}
					<label>{{ field.label_tag }}</label>
                    {{ field }}
                    {% endfor %}
					<button class="button margin-top-20 margin-bottom-20" type = "submit">Save Changes</button>
                </form>
            </div>

            {% comment %}
				<div class="col-md-4">
					<!-- Avatar -->
					<div class="edit-profile-photo">
						<img src="images/agent-02.jpg" alt="">
						<div class="change-photo-btn">
							<div class="photoUpload">
							    <span><i class="fa fa-upload"></i> Upload Photo</span>
							    <input type="file" class="upload" />
							</div>
						</div>
					</div>

				</div>
            {% endcomment %}

			</div>
		</div>

	</div>
</div>
{% endblock content %}